"" force 256 colors mode
set t_Co=256

"" display lines numbers
set number

"" colorscheme
set background=dark
"colorscheme hybrid
colorscheme jellybeans
"" encoding
set enc=utf-8
set fileencodings=utf-8

"" don't cut lines
set nowrap

"" tabs
set tabstop=4
set softtabstop=4
set shiftwidth=4

"" search stuff
set nohlsearch " Don't continue to highlight searched phrases.
set incsearch " But do highlight as you type your search.
set ignorecase " Make searches case-insensitive.

"" new 'syn on'
syntax enable

"" lighttpd config
au BufRead,BufNewFile /etc/lighttpd/*.conf,lighttpd.conf set filetype=lighttpd
"" nginx config
au BufRead,BufNewFile /etc/nginx/*,/usr/local/nginx/conf/* if &ft == '' | setfiletype nginx | endif

"" indent
filetype plugin indent on
set ai
set si

"" ctrlp stuff
set runtimepath^=~/.vim/bundle/ctrlp.vim
